'''try:
    doubtful code
except:
    handling code'''

num1=int(input("no1"))
num2=int(input("no2"))
try:
    res=num1/num2
    print("result",res)
except:
    print("exception occured")



print("new line")